
name: Run Today

on:
  push:
    branches:
      - main

# set environment variables from github secrets
env:
  GARMIN_TOKENS: ${{ secrets.GARMIN_TOKENS }}

# allow action to push to repo
permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23

      - name: Configure Git
        run: |
          git config --global user.email "ian@beckr.dev"
          git config --global user.name "Ian Becker"

      - name: Check if I ran today and update streak.txt
        run: |
          nix develop --impure --command just ran

      - name: Commit streak to GitHub if it changed
        run: |
          git diff --quiet HEAD -- streak.txt || (git commit -m "Update streak.txt" streak.txt && git push origin main)